export const roleAccess: Record<string, string[]> = {
  superadmin: [
    "/erp",
    "/erp/admissions",
    "/erp/new-admission",
    "/erp/enquiries",
    "/erp/assign-subject",
    "/erp/faculty",
    "/erp/fees",
    "/erp/filemanager",
    "/erp/followups",
    "/erp/pagesearch",
    "/erp/news",
  ],
  admin: ["/erp/fees" , "/erp"],
  teacher: ["/erp/marks", "/erp/progress-report", "/erp/student/attendance", "/erp"],
  student: ["/erp/student/attendance", "/erp/progress-report", "/erp/fees", "/erp"],
  public: [
    "/erp/login",
    "/erp/signup",
    "/erp/forgotpassword",
    "/erp/notfound",
    "/erp/email",
    "/erp/socialMedia",
    "/erp/faculty/signup",
    "/api/v2/admin/verify-invite",
    "/erp/admin/verify-invite",
    "/erp/faculty/complete-signup",
  ],
};
