export const roleAccess: Record<string, string[]> = {
  superadmin: [
    "/",
    "/admissions",
    "/new-admission",
    "/enquiries",
    "/assign-subject",
    "/faculty",
    "/fees",
    "/filemanager",
    "/followups",
    "/pagesearch",
    "/news",
  ],
  admin: ["/fees" , "/"],
  teacher: ["/marks", "/progress-report", "/student/attendance", "/"],
  student: ["/student/attendance", "/progress-report", "/fees", "/"],
  public: [
    "/login",
    "/signup",
    "/forgotpassword",
    "/notfound",
    "/email",
    "/socialMedia",
    "/faculty/signup",
    "/api/v2/admin/verify-invite",
    "/admin/verify-invite",
    "/faculty/complete-signup",
  ],
};
