import mongoose, { Schema } from "mongoose";

const admissionStudentInfoSchema = new Schema(
  {
    enrol_no: { type: String, trim: true, index: true },
    class: { type: String, trim: true },
    subjects: {
      first: String,
      second: String,
      third: String,
    },
    intermediate_board_name: String,
    intermediate_roll_number: { type: String, required: false },
    roll_number: { type: String, trim: true, index: true },
    full_name: {
      first_name: { type: String, required: true, trim: true },
      last_name: { type: String, trim: true },
      middle_name: { type: String, trim: true },
    },
    father_name: { type: String, trim: true },
    mother_name: { type: String, trim: true },
    date_of_birth: { type: Date, required: false },
    gender: { type: String, default: "Not Specified" },
    religion: String,
    category: String,
    isMinority: Boolean,
    isEWS_category: Boolean,
    nationality: { type: String, default: "Indian" },
    annual_family_income: Number,
    domicile: String,
    domicile_certitificate_number: { type: String },
    isAadharAvailable: Boolean,
    aadhar_number: { type: String, trim: true },
    fee_amt: { type: Number },
    fee_date: { type: String, trim: true },
    fee_div: { type: String, trim: true },
    special_category: String,
    state: String,
    district: String,
    address: String,
    pincode: String,
    isCorrespondenceAddressSame: Boolean,
    correspondence_state: String,
    correspondence_district: String,
    correspondence_address: String,
    correspondence_pincode: String,
    email_id: { type: String, trim: true, sparse: true, index: true },
    mobile_number: { type: String, trim: true, sparse: true },
    high_school_passing_year: String,
    high_school_board: String,
    high_school_max_marks: Number,
    high_school_marks_obtained: Number,
    intermediate_passing_status: String,
    status: { type: String, default: "Pending" },
    intermediate_isPassed: Boolean,
    intermediate_passing_year: String,
    intermediate_max_marks: Number,
    intermediate_marks_obtained: Number,
    intermediate_school_name: String,
    document_urls: {
      passport_photo: String,
      signature: String,
      category_certificate: String,
      domicile_certificate: String,
      aadhar_card: String,
      special_category_certificate: String,
      EWS_category_certificate: String,
    },
  },
  { collection: "unigrad_admission_student_info", timestamps: true }
);

export default mongoose.models.AdmissionStudentInfo ||
  mongoose.model("AdmissionStudentInfo", admissionStudentInfoSchema);

