import mongoose, { Schema } from "mongoose";

const admissionStudentInfoSchema = new Schema(
  {
    class: String,
    subjects: {
      first: String,
      second: String,
      third: String,
    },
    intermediate_board_name: String,
    intermediate_roll_number: { type: String , required:false},
    roll_number: { type: String},
    full_name: {
      first_name: { type: String, required: true },
      last_name: String,
      middle_name: String,
    },
    father_name: String,
    mother_name: String,
    date_of_birth: { type: Date, required: true },
    gender: { type: String, required: true },
    religion: String,
    category: String,
    isMinority: Boolean,
    isEWS_category: Boolean,
    nationality: { type: String, required: true },
    annual_family_income: Number,
    domicile: String,
    domicile_certitificate_number: { type: String },
    isAadharAvailable: Boolean,
    // aadhar_number: { type: String, unique: true },
    special_category: String,
    state: String,
    district: String,
    address: String,
    pincode: String,
    isCorrespondenceAddressSame: Boolean,
    correspondence_state: String,
    correspondence_district: String,
    correspondence_address: String,
    correspondence_pincode: String,
    email_id: { type: String, required: true, unique: true },
    mobile_number: { type: String, required: true, unique: true },
    high_school_passing_year: String,
    high_school_board: String,
    high_school_max_marks: Number,
    high_school_marks_obtained: Number,
    intermediate_passing_status: String,
    status:String,
    intermediate_isPassed: Boolean,
    intermediate_passing_year: String,
    intermediate_max_marks: Number,
    intermediate_marks_obtained: Number,
    intermediate_school_name: String,
    document_urls: {
      passport_photo: String,
      signature: String,
      category_certificate: String,
      domicile_certificate: String,
      aadhar_card: String,
      special_category_certificate: String,
      EWS_category_certificate: String,
    },
  },
  { collection: "unigrad_admission_student_info", timestamps: true }
);

export default mongoose.models.AdmissionStudentInfo ||
  mongoose.model("AdmissionStudentInfo", admissionStudentInfoSchema);
